spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_DB:db}:${DATABASE_PORT:5432}/${DATABASE_NAME:user-service}
    username: ${DATABASE_USER:user}
    password: ${DATABASE_PASSWORD:pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate.temp.user_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db.changelog-master.xml
server:
  port: ${SERVER_PORT:8080}
